<Project Sdk="Godot.NET.Sdk/4.8.0-dev.3">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="$(TargetName)" />
    <TrimmerRootAssembly Include="GodotSharp" />
  </ItemGroup>
</Project>